name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        texlive: [latest, TL2022-historic, TL2021-historic, TL2020-historic]
        # 多版本 TexLive 兼容性测试
        # 版本号选自：https://hub.docker.com/r/texlive/texlive/tags
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Tree All project
        run: sudo apt install tree;tree

      - name: Build pdf
        run: |
          docker run --rm -v "$(pwd)":/docs ghcr.io/liziwl/texlive-full-with-fonts:${{ matrix.texlive }} /bin/bash -c "make cleanall && make thesis"

      - name: Publish PDF as actions assets
        uses: actions/upload-artifact@v3
        with:
          name: Example-PDFs-texlive-${{ matrix.texlive }}
          path: |
            main.pdf
